//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLE_DataLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class AzureReindex
    {
        public int Id { get; set; }
        public int Status { get; set; }
        public string Message { get; set; }
        public int TotalToProcess { get; set; }
        public int TotalProcessed { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string UserName { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.Guid> LastModifiedBy { get; set; }
    }
}
