//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLE_DataLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlobResource
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public string FileUrl { get; set; }
        public long FileSizeInBytes { get; set; }
    
        public virtual DocumentResource DocumentResource { get; set; }
        public virtual ImageResource ImageResource { get; set; }
        public virtual ScormResource ScormResource { get; set; }
        public virtual VideoResource VideoResource { get; set; }
    }
}
