//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLE_DataLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentResource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContentResource()
        {
            this.VleResources = new HashSet<VleResource>();
        }
    
        public int Id { get; set; }
        public Nullable<int> LogoImageResourceId { get; set; }
        public bool HideLogo { get; set; }
    
        public virtual ImageResource ImageResource { get; set; }
        public virtual VleResource VleResource { get; set; }
        public virtual CurriculumResource CurriculumResource { get; set; }
        public virtual EventResource EventResource { get; set; }
        public virtual ProjectResource ProjectResource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VleResource> VleResources { get; set; }
    }
}
