//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLE_DataLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentResource
    {
        public int Id { get; set; }
        public string Author { get; set; }
        public string AuthorOrganisation { get; set; }
        public Nullable<System.DateTime> MetaDateItemPublished { get; set; }
    
        public virtual BlobResource BlobResource { get; set; }
        public virtual MarkdownResource MarkdownResource { get; set; }
        public virtual WebResource WebResource { get; set; }
        public virtual VleResource VleResource { get; set; }
    }
}
