//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLE_DataLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_node_property
    {
        public int id { get; set; }
        public int id_node { get; set; }
        public string name { get; set; }
        public string value { get; set; }
        public string search_key { get; set; }
    }
}
