//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLE_DataLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourcePermissionGroup
    {
        public int Id { get; set; }
        public int ResourceId { get; set; }
        public int PermissionGroupId { get; set; }
    
        public virtual PermissionGroup PermissionGroup { get; set; }
        public virtual VleResource VleResource { get; set; }
    }
}
