//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLE_DataLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScormLearning
    {
        public int Id { get; set; }
        public string StudentId { get; set; }
        public string StudentName { get; set; }
        public string LessonLocation { get; set; }
        public string Credit { get; set; }
        public string LessonStatus { get; set; }
        public string Entry { get; set; }
        public string Children { get; set; }
        public string ScoreChildren { get; set; }
        public string ScoreRaw { get; set; }
        public string ScoreMin { get; set; }
        public string ScoreMax { get; set; }
        public string TotalTime { get; set; }
        public string LessonMode { get; set; }
        public string Exit { get; set; }
        public string SuspendData { get; set; }
        public string LaunchData { get; set; }
        public int ModuleId { get; set; }
        public bool IsActive { get; set; }
        public bool InTrash { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.Guid> LastModifiedBy { get; set; }
    }
}
