//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLE_DataLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScormLearningSession
    {
        public int Id { get; set; }
        public int LearningId { get; set; }
        public System.Guid SessionId { get; set; }
        public string SessionTime { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
