//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLE_DataLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class VleResource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VleResource()
        {
            this.ResourceKeywords = new HashSet<ResourceKeyword>();
            this.ResourceRelations = new HashSet<ResourceRelation>();
            this.ResourceRelations1 = new HashSet<ResourceRelation>();
            this.ResourceTaxonomies = new HashSet<ResourceTaxonomy>();
            this.Status = new HashSet<Status>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public string FeaturedImageKey { get; set; }
        public string Organisation { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public int ContentTypeId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public bool IsActive { get; set; }
        public bool InTrash { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public bool IsFeatured { get; set; }
    
        public virtual ContentResource ContentResource { get; set; }
        public virtual ContentResource ContentResource1 { get; set; }
        public virtual Directorate Directorate { get; set; }
        public virtual DocumentResource DocumentResource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResourceKeyword> ResourceKeywords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResourceRelation> ResourceRelations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResourceRelation> ResourceRelations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResourceTaxonomy> ResourceTaxonomies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Status> Status { get; set; }
        public virtual VleResourceType VleResourceType { get; set; }
    }
}
