//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FazStock.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string ItemNumber { get; set; }
        public string ItemName { get; set; }
        public Nullable<double> ebayOurPrice { get; set; }
        public string ebayComptetionPrice { get; set; }
        public Nullable<double> StockLevel { get; set; }
        public Nullable<double> Sold { get; set; }
        public Nullable<double> StockLeft { get; set; }
        public string BestSelling { get; set; }
        public string Comments { get; set; }
    }
}
